### ISSUE TITLE
2 little things

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#67]
Error reported in course CSC2-140 on page 2DimensionalIterationImageProcessing by user tdelaubenfels tdelaubenfels@cornellcollege.edu
Explaining the negative image of the Luther bell, the paragraph refers to newimg while the code use win.
BTW, the input validation while loop in Ch. 8 always gives a times out message. Works great in Idle.

**Comment by bnmnetp** [comment]
Good catches.

1.  That is a holdover from before we were able to animate the image processing.  In fact win is not an image but a window object.  I just need to remove any reference to a second image since we are updating the original image.

2.  The author of the example set a time limit that was meant to be 60 seconds but made it 60 msecs instead.
