### ISSUE TITLE
Error: Unable to save to source_code 

### ISSUE THREAD

**Issue by andreacortis** [RunestoneInteractive/thinkcspy#95]
Hello, I am getting this problem when running `runestone build`

```
This should only affect the grading interface. Everything else should be fine.
Unable to save to source_code table in datafile__init__.py. Possible problems:                                                                                           
  1. dburl or course_id are not set in conf.py for your book
  2. unable to connect to the database using dburl
```

When I try to run the interactive code in the HTML it pops up a message saying that it can't sve the code.

Am I missing some step here?

Thanks

**Comment by bnmnetp** [comment]
Hi,

My guess is that you are running `runestone serve` That command just starts up a minimal webserver that allows you to see and interact with all of the pages.  It does not have any support for the Runestone API for saving answers etc.  If you want to save answers and have full support then you should either use runestone.academy or you should set up your own RunestoneServer and database.  

If you don't care about saving work and having an instructor interface, then you should edit the pavement.py file and change the setting for use_runestone_services to false.  If that parameter is false you will not get the message that it can't save the code because it won't even try.

**Comment by andreacortis** [comment]
got you. That explains. Thanks for the answer!
